welcome-message: Hello from the first microservice!
twitter-stream:
  mock:
    enable: true
    period-between-tweets: 2000
  filter-keywords:
    - Java
    - Kafka
    - Spring
    - Elasticstack
    - Microservices
