welcome-message: Assalamu aleykum!
twitter-stream:
  mock:
    enable: true
    period-between-tweets: 5000
  filter-keywords:
    - Java
    - Kafka
    - Spring
    - Elasticstack
    - Microservices
